### ISSUE TITLE
Example output file?

### ISSUE THREAD

**Issue by stianlagstad** [ChimeRScope/ChimeRScope#2]
Hi,

I would like to know if the output data that ChimeRScope produces can be used with https://github.com/stianlagstad/chimeraviz. Do you have any example output files that you can share?

Thank you!

**Comment by ChimeRScope** [comment]
Hi. Sorry that I am no longer maintaining the scripts. You may contact the corresponding author for that. As far as I remember, ChimeRScope output is not direct compatible but you can write a small script to adjust it.


Best




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Stian Lågstad"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月12日(星期四) 晚上7:13
收件人:&nbsp;"ChimeRScope/ChimeRScope"<ChimeRScope@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ChimeRScope/ChimeRScope] Example output file? (#2)





 
Hi,
 
I would like to know if the output data that ChimeRScope produces can be used with https://github.com/stianlagstad/chimeraviz. Do you have any example output files that you can share?
 
Thank you!

**Comment by stianlagstad** [comment]
Thank you for the response. If it's no longer maintained then I won't add support for the data in chimeraviz.
